name: Justine Bloome
favicon: null
layout_spectrum: 1
typography_spectrum: 0.016077940119430423
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.11847789795137942
  lightness: 0.8626082895789295
  saturation: 0.9863306048791856
  rhythmicContrast: 0.8975733511615545
purpose: []
